# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/malapati/fast-code-2-pro/cnn_from_scratch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/malapati/fast-code-2-pro/cnn_from_scratch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/malapati/fast-code-2-pro/cnn_from_scratch/CMakeFiles /home/malapati/fast-code-2-pro/cnn_from_scratch//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/malapati/fast-code-2-pro/cnn_from_scratch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neural_net_in_cpp

# Build rule for target.
neural_net_in_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neural_net_in_cpp
.PHONY : neural_net_in_cpp

# fast build rule for target.
neural_net_in_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/build
.PHONY : neural_net_in_cpp/fast

src/Conv2d.o: src/Conv2d.cpp.o
.PHONY : src/Conv2d.o

# target to build an object file
src/Conv2d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Conv2d.cpp.o
.PHONY : src/Conv2d.cpp.o

src/Conv2d.i: src/Conv2d.cpp.i
.PHONY : src/Conv2d.i

# target to preprocess a source file
src/Conv2d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Conv2d.cpp.i
.PHONY : src/Conv2d.cpp.i

src/Conv2d.s: src/Conv2d.cpp.s
.PHONY : src/Conv2d.s

# target to generate assembly for a file
src/Conv2d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Conv2d.cpp.s
.PHONY : src/Conv2d.cpp.s

src/Dropout.o: src/Dropout.cpp.o
.PHONY : src/Dropout.o

# target to build an object file
src/Dropout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Dropout.cpp.o
.PHONY : src/Dropout.cpp.o

src/Dropout.i: src/Dropout.cpp.i
.PHONY : src/Dropout.i

# target to preprocess a source file
src/Dropout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Dropout.cpp.i
.PHONY : src/Dropout.cpp.i

src/Dropout.s: src/Dropout.cpp.s
.PHONY : src/Dropout.s

# target to generate assembly for a file
src/Dropout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Dropout.cpp.s
.PHONY : src/Dropout.cpp.s

src/FullyConnected.o: src/FullyConnected.cpp.o
.PHONY : src/FullyConnected.o

# target to build an object file
src/FullyConnected.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/FullyConnected.cpp.o
.PHONY : src/FullyConnected.cpp.o

src/FullyConnected.i: src/FullyConnected.cpp.i
.PHONY : src/FullyConnected.i

# target to preprocess a source file
src/FullyConnected.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/FullyConnected.cpp.i
.PHONY : src/FullyConnected.cpp.i

src/FullyConnected.s: src/FullyConnected.cpp.s
.PHONY : src/FullyConnected.s

# target to generate assembly for a file
src/FullyConnected.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/FullyConnected.cpp.s
.PHONY : src/FullyConnected.cpp.s

src/LinearLRScheduler.o: src/LinearLRScheduler.cpp.o
.PHONY : src/LinearLRScheduler.o

# target to build an object file
src/LinearLRScheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/LinearLRScheduler.cpp.o
.PHONY : src/LinearLRScheduler.cpp.o

src/LinearLRScheduler.i: src/LinearLRScheduler.cpp.i
.PHONY : src/LinearLRScheduler.i

# target to preprocess a source file
src/LinearLRScheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/LinearLRScheduler.cpp.i
.PHONY : src/LinearLRScheduler.cpp.i

src/LinearLRScheduler.s: src/LinearLRScheduler.cpp.s
.PHONY : src/LinearLRScheduler.s

# target to generate assembly for a file
src/LinearLRScheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/LinearLRScheduler.cpp.s
.PHONY : src/LinearLRScheduler.cpp.s

src/MNISTDataLoader.o: src/MNISTDataLoader.cpp.o
.PHONY : src/MNISTDataLoader.o

# target to build an object file
src/MNISTDataLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/MNISTDataLoader.cpp.o
.PHONY : src/MNISTDataLoader.cpp.o

src/MNISTDataLoader.i: src/MNISTDataLoader.cpp.i
.PHONY : src/MNISTDataLoader.i

# target to preprocess a source file
src/MNISTDataLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/MNISTDataLoader.cpp.i
.PHONY : src/MNISTDataLoader.cpp.i

src/MNISTDataLoader.s: src/MNISTDataLoader.cpp.s
.PHONY : src/MNISTDataLoader.s

# target to generate assembly for a file
src/MNISTDataLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/MNISTDataLoader.cpp.s
.PHONY : src/MNISTDataLoader.cpp.s

src/MaxPool.o: src/MaxPool.cpp.o
.PHONY : src/MaxPool.o

# target to build an object file
src/MaxPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/MaxPool.cpp.o
.PHONY : src/MaxPool.cpp.o

src/MaxPool.i: src/MaxPool.cpp.i
.PHONY : src/MaxPool.i

# target to preprocess a source file
src/MaxPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/MaxPool.cpp.i
.PHONY : src/MaxPool.cpp.i

src/MaxPool.s: src/MaxPool.cpp.s
.PHONY : src/MaxPool.s

# target to generate assembly for a file
src/MaxPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/MaxPool.cpp.s
.PHONY : src/MaxPool.cpp.s

src/NetworkModel.o: src/NetworkModel.cpp.o
.PHONY : src/NetworkModel.o

# target to build an object file
src/NetworkModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/NetworkModel.cpp.o
.PHONY : src/NetworkModel.cpp.o

src/NetworkModel.i: src/NetworkModel.cpp.i
.PHONY : src/NetworkModel.i

# target to preprocess a source file
src/NetworkModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/NetworkModel.cpp.i
.PHONY : src/NetworkModel.cpp.i

src/NetworkModel.s: src/NetworkModel.cpp.s
.PHONY : src/NetworkModel.s

# target to generate assembly for a file
src/NetworkModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/NetworkModel.cpp.s
.PHONY : src/NetworkModel.cpp.s

src/ReLU.o: src/ReLU.cpp.o
.PHONY : src/ReLU.o

# target to build an object file
src/ReLU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/ReLU.cpp.o
.PHONY : src/ReLU.cpp.o

src/ReLU.i: src/ReLU.cpp.i
.PHONY : src/ReLU.i

# target to preprocess a source file
src/ReLU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/ReLU.cpp.i
.PHONY : src/ReLU.cpp.i

src/ReLU.s: src/ReLU.cpp.s
.PHONY : src/ReLU.s

# target to generate assembly for a file
src/ReLU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/ReLU.cpp.s
.PHONY : src/ReLU.cpp.s

src/Sigmoid.o: src/Sigmoid.cpp.o
.PHONY : src/Sigmoid.o

# target to build an object file
src/Sigmoid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Sigmoid.cpp.o
.PHONY : src/Sigmoid.cpp.o

src/Sigmoid.i: src/Sigmoid.cpp.i
.PHONY : src/Sigmoid.i

# target to preprocess a source file
src/Sigmoid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Sigmoid.cpp.i
.PHONY : src/Sigmoid.cpp.i

src/Sigmoid.s: src/Sigmoid.cpp.s
.PHONY : src/Sigmoid.s

# target to generate assembly for a file
src/Sigmoid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Sigmoid.cpp.s
.PHONY : src/Sigmoid.cpp.s

src/SoftmaxClassifier.o: src/SoftmaxClassifier.cpp.o
.PHONY : src/SoftmaxClassifier.o

# target to build an object file
src/SoftmaxClassifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/SoftmaxClassifier.cpp.o
.PHONY : src/SoftmaxClassifier.cpp.o

src/SoftmaxClassifier.i: src/SoftmaxClassifier.cpp.i
.PHONY : src/SoftmaxClassifier.i

# target to preprocess a source file
src/SoftmaxClassifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/SoftmaxClassifier.cpp.i
.PHONY : src/SoftmaxClassifier.cpp.i

src/SoftmaxClassifier.s: src/SoftmaxClassifier.cpp.s
.PHONY : src/SoftmaxClassifier.s

# target to generate assembly for a file
src/SoftmaxClassifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/SoftmaxClassifier.cpp.s
.PHONY : src/SoftmaxClassifier.cpp.s

src/Tensor.o: src/Tensor.cpp.o
.PHONY : src/Tensor.o

# target to build an object file
src/Tensor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Tensor.cpp.o
.PHONY : src/Tensor.cpp.o

src/Tensor.i: src/Tensor.cpp.i
.PHONY : src/Tensor.i

# target to preprocess a source file
src/Tensor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Tensor.cpp.i
.PHONY : src/Tensor.cpp.i

src/Tensor.s: src/Tensor.cpp.s
.PHONY : src/Tensor.s

# target to generate assembly for a file
src/Tensor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/Tensor.cpp.s
.PHONY : src/Tensor.cpp.s

src/main_org.o: src/main_org.cpp.o
.PHONY : src/main_org.o

# target to build an object file
src/main_org.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/main_org.cpp.o
.PHONY : src/main_org.cpp.o

src/main_org.i: src/main_org.cpp.i
.PHONY : src/main_org.i

# target to preprocess a source file
src/main_org.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/main_org.cpp.i
.PHONY : src/main_org.cpp.i

src/main_org.s: src/main_org.cpp.s
.PHONY : src/main_org.s

# target to generate assembly for a file
src/main_org.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_in_cpp.dir/build.make CMakeFiles/neural_net_in_cpp.dir/src/main_org.cpp.s
.PHONY : src/main_org.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... neural_net_in_cpp"
	@echo "... src/Conv2d.o"
	@echo "... src/Conv2d.i"
	@echo "... src/Conv2d.s"
	@echo "... src/Dropout.o"
	@echo "... src/Dropout.i"
	@echo "... src/Dropout.s"
	@echo "... src/FullyConnected.o"
	@echo "... src/FullyConnected.i"
	@echo "... src/FullyConnected.s"
	@echo "... src/LinearLRScheduler.o"
	@echo "... src/LinearLRScheduler.i"
	@echo "... src/LinearLRScheduler.s"
	@echo "... src/MNISTDataLoader.o"
	@echo "... src/MNISTDataLoader.i"
	@echo "... src/MNISTDataLoader.s"
	@echo "... src/MaxPool.o"
	@echo "... src/MaxPool.i"
	@echo "... src/MaxPool.s"
	@echo "... src/NetworkModel.o"
	@echo "... src/NetworkModel.i"
	@echo "... src/NetworkModel.s"
	@echo "... src/ReLU.o"
	@echo "... src/ReLU.i"
	@echo "... src/ReLU.s"
	@echo "... src/Sigmoid.o"
	@echo "... src/Sigmoid.i"
	@echo "... src/Sigmoid.s"
	@echo "... src/SoftmaxClassifier.o"
	@echo "... src/SoftmaxClassifier.i"
	@echo "... src/SoftmaxClassifier.s"
	@echo "... src/Tensor.o"
	@echo "... src/Tensor.i"
	@echo "... src/Tensor.s"
	@echo "... src/main_org.o"
	@echo "... src/main_org.i"
	@echo "... src/main_org.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

